### ISSUE TITLE
Is this library compatible with Objective C?

### ISSUE THREAD

**Issue by jlubeck** [marcosgriselli/ViewAnimator#13]
I tried using it and the only exposed method for a view is "animateRandomWithInterval"

Thanks

**Comment by marcosgriselli** [comment]
Right now it's not due to the default animations depending on the `AnimationType` enum which cannot be represented in Objective-C as they use associated values. 

From [Xcode 6.3 release notes](https://developer.apple.com/library/content/documentation/Xcode/Conceptual/RN-Xcode-Archive/Chapters/xc6_release_notes.html#//apple_ref/doc/uid/TP40016994-CH4-SW26): 

> Swift Language Enhancements
> ...
> Swift enums can now be exported to Objective-C using the @objc attribute. @objc enums must declare an integer raw type, and cannot be generic or use associated values. Because Objective-C enums are not namespaced, enum cases are imported into Objective-C as the concatenation of the enum name and case name.

[Source](https://stackoverflow.com/a/30480399/2892512)

**Comment by CavalcanteLeo** [comment]
=(
