### ISSUE TITLE
No animation for Header and Footer of UICollectionView or UITableView

### ISSUE THREAD

**Issue by dillidon** [marcosgriselli/ViewAnimator#45]
Thats all)

**Comment by dillidon** [comment]
One more thing - views (headers, cells and footers) should be sorted... just caught it in my project...

**Comment by marcosgriselli** [comment]
After looking into this issue I believe each app should manage their own selection of views that need to be animated. I can't remember if this issue was created before we implemented the `animate(views: ...` API. It's not that complicated and we can even add a function that grabs all cells and headers in the docs. This is the result of animating headers and footers: 

![header_footer_animations](https://user-images.githubusercontent.com/14804033/58212726-31a86880-7cc6-11e9-8ce7-6b62134191ce.gif)

And here's a quick example of how views can be picked for animations: 

```swift 
private func viewsToAnimate(in tableView: UITableView) -> [UIView] {
    var views = [UIView]()
    tableView.tableHeaderView.flatMap { views.append($0) }
    tableView.headerView(forSection: 0).flatMap { views.append($0) }
    views.append(contentsOf: tableView.visibleCells)
    tableView.footerView(forSection: 0).flatMap { views.append($0) }
    tableView.tableFooterView.flatMap { views.append($0) }
    return views
}
```

I know this is super late but I hope this helps someone trying to achieve this result.
