### ISSUE TITLE
UIView unexpectedly changes position after animation

### ISSUE THREAD

**Issue by kennyDang** [marcosgriselli/ViewAnimator#51]
## Expected Behavior
I have a button that uses an `AnimationType(.bottom, offset: 10)` animation whenever it is tapped.
The button should perform the animation and return to its original position.

## Actual Behavior
The button performs the animation but changes it's y position with every tap. For example, here is the CGRect of the button for each button animation: 
```
(247.6666666666667, 10.0, 106.33333333333334, 30.0)
(247.6666666666667, 20.0, 106.33333333333334, 30.0)
(247.6666666666667, 30.0, 106.33333333333334, 30.0)
(247.6666666666667, 40.0, 106.33333333333334, 30.0)
```

## Steps to Reproduce the Problem

  1. Programmatic views with autolayout
  2. Press button and animate it: `UIView.animate(views: [button],
                           animations: [buttonAnimation],
                           reversed: true,
                           initialAlpha: 1.0,
                           finalAlpha: 0.0,
                           completion: {print(self.button.frame)})`
## Specifications

  - Version: 2.2.0
  - Platform: iOS 11
  - Subsystem:

**Comment by marcosgriselli** [comment]
Well, it's been a long time but better late than never. @kennyDang why is the expected behavior to return to its original position? The `reversed` property determines if an animation should run in the opposite direction. What you're looking for is probably `autoreverses` which we can add to future versions of the library.
